In [1]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

import pandas as pd
import numpy as np


In [2]:
iris = load_iris()

iris_data = iris.data
iris_label = iris.target
print('iris target value:', iris_label)
print('iris target name:', iris.target_names)

iris target value: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
iris target name: ['setosa' 'versicolor' 'virginica']


In [3]:
iris_df = pd.DataFrame(data=iris_data, columns=iris.feature_names)
iris_df['label'] = iris.target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     label  
0        0  
1        0  
2        0  
3        0  
4        0  
..     ...  
145      2  
146      2  
147      2  
148      2  
149      2  

[150 rows x 5 columns]

In [4]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [5]:
iris.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [6]:
train_x, test_x, train_y, test_y = train_test_split(iris_data, iris_label, 
                                                   test_size=0.2, random_state=11)

In [7]:
train_y

array([0, 2, 2, 0, 0, 2, 2, 1, 0, 1, 1, 2, 0, 1, 2, 1, 1, 0, 2, 0, 2, 2,
       1, 2, 1, 0, 0, 1, 0, 0, 2, 2, 2, 0, 0, 0, 1, 0, 1, 2, 2, 1, 1, 2,
       2, 0, 1, 1, 2, 2, 2, 0, 2, 0, 0, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2,
       1, 0, 0, 0, 1, 1, 1, 2, 1, 0, 1, 2, 0, 2, 2, 1, 0, 0, 0, 2, 1, 0,
       2, 1, 2, 0, 0, 1, 1, 2, 1, 2, 2, 1, 1, 2, 2, 0, 1, 2, 0, 2, 2, 0,
       1, 2, 0, 1, 1, 1, 0, 1, 1, 1])

In [8]:
test_y

array([2, 2, 2, 1, 2, 0, 1, 0, 0, 1, 2, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [9]:
classifier = DecisionTreeClassifier(random_state=11)

classifier.fit(train_x, train_y)

DecisionTreeClassifier(random_state=11)

In [10]:
pred = classifier.predict(test_x)
pred

array([2, 2, 1, 1, 2, 0, 1, 0, 0, 1, 1, 1, 1, 2, 2, 0, 2, 1, 2, 2, 1, 0,
       0, 1, 0, 0, 2, 1, 0, 1])

In [11]:
from sklearn.metrics import accuracy_score
print(f"accuracy: {accuracy_score(test_y, pred):.4f}")

accuracy: 0.9333


In [12]:
def get_accuracy(test_y, pred) -> float:
    assert len(test_y) == len(pred)
    cnt = 0
    for i in range(len(test_y)):
        if test_y[i] == pred[i]:
            cnt += 1
    return cnt / len(test_y)

acc = get_accuracy(test_y, pred)
print(acc)

0.9333333333333333


## train_test_split의 사용

In [13]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

classifier = DecisionTreeClassifier()
iris_data = load_iris()

train_x, test_x, train_y, test_y = train_test_split(iris_data.data, iris_data.target,
                                                   test_size=0.3, random_state=121)

In [14]:
classifier.fit(train_x, train_y)

pred = classifier.predict(test_x)

print(f"accuracy: {accuracy_score(test_y, pred):.4f}")

accuracy: 0.9556


## Cross Validation 사용
고정된 학습 데이터와 테스트 데이터로 평가를 하다 보면 테스트 데이터에만 최적의 성능을 발휘할 수 있도록 편향되게 모델을 유도하는 경향이 생기게 된다.  
이러한 문제점을 개선하기 위해 cross validation을 사용하여 다양한 학습과 평가를 수행한다.
- k-fold cross validation  
k개의 data fold set을 만들어 k번만큼 각 fold set에 학습과 검증 평가를 반복적으로 수행하는 방법.

In [15]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold

import numpy as np

iris = load_iris()

data = iris.data
label = iris.target

classifier = DecisionTreeClassifier(random_state=156)

# kfold (k = 5)
kfold = KFold(n_splits=5)
cross_val_accuracy = []

print(f"dataset 크기: {data.shape[0]}")

dataset 크기: 150


In [16]:
# kfold.split 확인
for train_idx, test_idx in kfold.split(data):
    print(train_idx, test_idx)

[ 30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45  46  47
  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149] [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  60  61  62  63  64  65
  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81  82  83
  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99 100 101
 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117 118 119
 120 121 122 123 124 125 126 127 128 129 130 131 132 1

In [20]:
n_iter = 0

for train_idx, test_idx in kfold.split(data):
    train_x, test_x = data[train_idx], data[test_idx]
    train_y, test_y = label[train_idx], label[test_idx]
    
    classifier.fit(train_x, train_y)
    pred = classifier.predict(test_x)
    n_iter += 1
    accuracy = np.round(accuracy_score(test_y, pred), 4)
    train_size, test_size = train_x.shape[0], test_x.shape[0]
    print(f"#{n_iter} cross validation accuracy: {accuracy}, 학습 데이터 크기: {train_size}, 검증 데이터 크기: {test_size}")
    print(f"#{n_iter} test set index: {test_idx}\n")
    cross_val_accuracy.append(accuracy)
    
# 평균 정확도 계산
print(f"평균 검증 정확도: {np.mean(cross_val_accuracy)}")

#1 cross validation accuracy: 1.0, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#1 test set index: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

#2 cross validation accuracy: 0.9667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#2 test set index: [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]

#3 cross validation accuracy: 0.8667, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#3 test set index: [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]

#4 cross validation accuracy: 0.9333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#4 test set index: [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]

#5 cross validation accuracy: 0.7333, 학습 데이터 크기: 120, 검증 데이터 크기: 30
#5 test set index: [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]

평균 검증 정확도: 0.9


- stratified k-fold cross validation  
불균형한 분포도를 가진 label 데이터 집합을 위한 방법.  
불균형한 분포도를 가졌다는 것은 특정 레이블 값이 특이하게 많거나 매우 적어서 값의 분포가 한쪽으로 치우치는 것을 말한다.
